version: '3.8'

services:
  app:
    build: .
    container_name: myapp_container
    volumes:
      - ./myapp:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - myapp_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: arib-task
    ports:
      - "3306:3306"
    networks:
      - myapp_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./myapp:/var/www/html
    networks:
      - myapp_network
    depends_on:
      - app

networks:
  myapp_network:
    driver: bridge
